### ISSUE TITLE
Retrieve data from the default graph of a remote endpoint

### ISSUE THREAD

**Issue by andybywire** [AKSW/jekyll-rdf#279]
I'm experimenting with using Fuseki as my data source (as opposed to a static file) in order to bring a reasoner into my app. I've been able to get connected with a Fuseki named graph running on localhost with this configuration (as described in the docs):
```
jekyll_rdf:
    remote:
      endpoint: "http://localhost:3030/UXM/sparql"
      default_graph: "https://www.uxmethods.org/g1"
```
Because of the way online updates work with Fuseki, however, I'd really rather query the default graph. Omitting the `default_graph` parameter, however, results in a jekyll error. No combination of `https://www.uxmethods.org/default, default, DEFAULT, etc` I've tried has gotten me to the default graph. 

Is accessing the default graph possible? (And is it something that I hope isn't totally obvious 😬). If there's a detail missing in the README that might help clarify this, I'd be happy to add it in and submit a pull request.

Thank you!

FWIW: I'm not sure if this is a proper issue or just me missing something, but I can't get my head around it, so posting here. Either way, thanks a ton for this tool—it's been a great way to explore building static web applications backed by RDF.
